//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Boilerplate.Core.Models.GeneratedModels
{
	/// <summary>Monthly News Container</summary>
	[PublishedModel("monthlyNewsContainer")]
	public partial class MonthlyNewsContainer : PublishedContentModel, ILayout
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		public new const string ModelTypeAlias = "monthlyNewsContainer";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<MonthlyNewsContainer, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public MonthlyNewsContainer(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Disallow Search Engine Navigation: Prevents search engines to follow links from the page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[ImplementPropertyType("disallowSearchEngineNavigation")]
		public virtual bool DisallowSearchEngineNavigation => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetDisallowSearchEngineNavigation(this, _publishedValueFallback);

		///<summary>
		/// Disallow Search Engine To Index Page: Prevent page from appearing in search engine results.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[ImplementPropertyType("disallowSearchEngineToIndexPage")]
		public virtual bool DisallowSearchEngineToIndexPage => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetDisallowSearchEngineToIndexPage(this, _publishedValueFallback);

		///<summary>
		/// Hide In Left Navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[ImplementPropertyType("hideInLeftNavigation")]
		public virtual bool HideInLeftNavigation => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetHideInLeftNavigation(this, _publishedValueFallback);

		///<summary>
		/// Description: This description is included in link lists and on Google search results. Max 160 characters.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaDescription")]
		public virtual string MetaDescription => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetMetaDescription(this, _publishedValueFallback);

		///<summary>
		/// Navigation Name: Use this name for the page in the navigation.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("navigationName")]
		public virtual string NavigationName => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetNavigationName(this, _publishedValueFallback);

		///<summary>
		/// Page Alias: Another URL to the page. Multiple URLs are separated by commas.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageAlias")]
		public virtual string PageAlias => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetPageAlias(this, _publishedValueFallback);

		///<summary>
		/// Page Script: This script is rendered at the end of the body tag. Include your own script tags.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageScript")]
		public virtual string PageScript => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetPageScript(this, _publishedValueFallback);

		///<summary>
		/// Page URL: Alternative page name. Alters the last part of the URL.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageURL")]
		public virtual string PageUrl => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetPageUrl(this, _publishedValueFallback);

		///<summary>
		/// Share Image: Image used for e.g. social media links, widgets etc.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("shareImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ShareImage => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetShareImage(this, _publishedValueFallback);

		///<summary>
		/// Hide In Navigation: The page can be accessed but is not displayed in the navigation.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetUmbracoNaviHide(this, _publishedValueFallback);

		///<summary>
		/// Window Title And Social Media Header: Enter something short and compelling (max 60 characters) about the content. Is used as a header when sharing on Social Media.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.1.0+b0a4a92f578580e6045a0cf58a4ba5ff65fc4187")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("windowTitleAndSocialMediaHeader")]
		public virtual string WindowTitleAndSocialMediaHeader => global::Boilerplate.Core.Models.GeneratedModels.Layout.GetWindowTitleAndSocialMediaHeader(this, _publishedValueFallback);
	}
}
